const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const FILTER_USERS = 'FILTER_USERS';

export {
    ADD_USER_SUCCESS,
    FETCH_USER_SUCCESS,
    FETCH_USERS_SUCCESS,
    REMOVE_USER_SUCCESS,
    UPDATE_USER_SUCCESS,
    FILTER_USERS
};
